include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false

analyzer:
  errors:
    # The deprecated keyEventManager/handleKeyData APIs are the only way to
    # programmatically inject key events. The new addHandler API is for listeners.
    deprecated_member_use: ignore
