import 'dart:io';
import 'package:path/path.dart' as path;

/// Generates a synthetic main.dart file that wraps the user's app
/// with runtime AI dev tools.
class SyntheticMainGenerator {
  /// Read the package name from pubspec.yaml
  static Future<String> _getPackageName(String projectDir) async {
    final pubspecPath = path.join(projectDir, 'pubspec.yaml');
    print('📦 [SyntheticMainGenerator] Reading pubspec.yaml from: $pubspecPath');
    final pubspecContent = await File(pubspecPath).readAsString();
    // Simple regex to extract name: value
    final match =
        RegExp(r'^name:\s*(\S+)', multiLine: true).firstMatch(pubspecContent);
    if (match == null) {
      print('❌ [SyntheticMainGenerator] Could not find package name in pubspec.yaml');
      throw Exception('Could not find package name in pubspec.yaml');
    }
    final packageName = match.group(1)!;
    print('📦 [SyntheticMainGenerator] Found package name: $packageName');
    return packageName;
  }

  /// Generate synthetic main file for the given project.
  ///
  /// [projectDir] - Absolute path to the Flutter project root
  /// [userMainPath] - Path to user's main.dart relative to project root
  ///
  /// Returns the path to the generated synthetic main file.
  static Future<String> generate({
    required String projectDir,
    String userMainPath = 'lib/main.dart',
  }) async {
    print('');
    print('🔧 [SyntheticMainGenerator] ========================================');
    print('🔧 [SyntheticMainGenerator] Generating synthetic main...');
    print('🔧 [SyntheticMainGenerator] Project directory: $projectDir');
    print('🔧 [SyntheticMainGenerator] User main path: $userMainPath');

    final dartToolDir = path.join(projectDir, '.dart_tool');
    final syntheticMainPath = path.join(dartToolDir, 'parott_debug_main.dart');
    print('🔧 [SyntheticMainGenerator] Synthetic main path: $syntheticMainPath');

    // Ensure .dart_tool directory exists
    await Directory(dartToolDir).create(recursive: true);
    print('🔧 [SyntheticMainGenerator] Created .dart_tool directory');

    // Get package name for proper package import (works for web builds)
    final packageName = await _getPackageName(projectDir);

    // Convert lib/main.dart to package import path
    // e.g., lib/main.dart -> package:example_app/main.dart
    final mainFile = userMainPath.replaceFirst('lib/', '');
    final userMainImport = 'package:$packageName/$mainFile';
    print('🔧 [SyntheticMainGenerator] User main import: $userMainImport');

    final syntheticMain = '''
// Generated by Parott - DO NOT EDIT
// This file wraps the user's app with runtime AI dev tools.
// It is automatically generated and should not be committed to version control.

import 'package:runtime_ai_dev_tools/runtime_ai_dev_tools.dart';
import '$userMainImport' as user_app;

void main() {
  // Initialize custom binding that wraps root widget with DebugOverlayWrapper
  // and register all service extensions (screenshot, tap, type, scroll)
  RuntimeAiDevTools.initForSyntheticMain();

  // Call user's main - the binding will intercept runApp() automatically
  // Note: We don't await since user's main() may return void (not Future<void>)
  user_app.main();
}
''';

    await File(syntheticMainPath).writeAsString(syntheticMain);

    print('🔧 [SyntheticMainGenerator] ----------------------------------------');
    print('🔧 [SyntheticMainGenerator] Generated synthetic main content:');
    print('🔧 [SyntheticMainGenerator] ----------------------------------------');
    for (final line in syntheticMain.split('\n')) {
      print('🔧 [SyntheticMainGenerator]   $line');
    }
    print('🔧 [SyntheticMainGenerator] ----------------------------------------');
    print('🔧 [SyntheticMainGenerator] ========================================');
    print('');

    return syntheticMainPath;
  }

  /// Clean up generated synthetic main file.
  static Future<void> cleanup(String projectDir) async {
    final syntheticMainPath =
        path.join(projectDir, '.dart_tool', 'parott_debug_main.dart');
    final file = File(syntheticMainPath);
    if (await file.exists()) {
      await file.delete();
    }
  }
}
