import 'dart:io';
import 'package:path/path.dart' as path;

import 'bundled_devtools_code.dart';

/// Generates a synthetic main.dart file that wraps the user's app
/// with runtime AI dev tools.
class SyntheticMainGenerator {
  /// Read the package name from pubspec.yaml
  static Future<String> _getPackageName(String projectDir) async {
    final pubspecPath = path.join(projectDir, 'pubspec.yaml');
    final pubspecContent = await File(pubspecPath).readAsString();
    // Simple regex to extract name: value
    final match = RegExp(
      r'^name:\s*(\S+)',
      multiLine: true,
    ).firstMatch(pubspecContent);
    if (match == null) {
      throw Exception('Could not find package name in pubspec.yaml');
    }
    return match.group(1)!;
  }

  /// Generate synthetic main file for the given project.
  ///
  /// [projectDir] - Absolute path to the Flutter project root
  /// [userMainPath] - Path to user's main.dart relative to project root
  ///
  /// Returns the path to the generated synthetic main file.
  static Future<String> generate({
    required String projectDir,
    String userMainPath = 'lib/main.dart',
  }) async {
    final dartToolDir = path.join(projectDir, '.dart_tool');
    final syntheticMainPath = path.join(dartToolDir, 'vide_debug_main.dart');

    // Ensure .dart_tool directory exists
    await Directory(dartToolDir).create(recursive: true);

    // Get package name for proper package import (works for web builds)
    final packageName = await _getPackageName(projectDir);

    // Convert lib/main.dart to package import path
    // e.g., lib/main.dart -> package:example_app/main.dart
    final mainFile = userMainPath.replaceFirst('lib/', '');
    final userMainImport = 'package:$packageName/$mainFile';

    final syntheticMain =
        '''
// Generated by Vide CLI - DO NOT EDIT
// This file wraps the user's app with runtime AI dev tools.
// It is automatically generated and should not be committed to version control.

$bundledImports
// === User app import ===
import '$userMainImport' as user_app;

$bundledCode

bool _runtimeAiDevToolsInitialized = false;

void _initRuntimeAiDevTools() {
  if (_runtimeAiDevToolsInitialized) {
    return;
  }
  _runtimeAiDevToolsInitialized = true;
  _registerScreenshotExtension();
  _registerTapExtension();
  _registerTypeExtension();
  _registerScrollExtension();
}

void main() {
  _DebugWidgetsFlutterBinding.ensureInitialized();
  _initRuntimeAiDevTools();
  user_app.main();
}
''';

    await File(syntheticMainPath).writeAsString(syntheticMain);

    return syntheticMainPath;
  }

  /// Clean up generated synthetic main file.
  static Future<void> cleanup(String projectDir) async {
    final syntheticMainPath = path.join(
      projectDir,
      '.dart_tool',
      'vide_debug_main.dart',
    );
    final file = File(syntheticMainPath);
    if (await file.exists()) {
      await file.delete();
    }
  }
}
